name: Upload Figma Export to Q

on:
  repository_dispatch:
    types: [process-figma]
  workflow_dispatch:
    inputs:
      zipUrl:
        description: 'URL of the Figma export ZIP file'
        required: true
        type: string
      id:
        description: 'Production ID'
        required: true
        type: string

jobs:
  process-figma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Process Figma Export
        run: npm run process-figma "${{ github.event_name == 'repository_dispatch' && github.event.client_payload.zipUrl || inputs.zipUrl }}" "${{ github.event_name == 'repository_dispatch' && github.event.client_payload.id || inputs.id }}"

      # Run Svelte
      - name: Run Svelte
        run: npm run build

      # Install Q-CLI
      - name: Install node packages
        run: npm install -g @nzz/q-cli
      - name: Run Q cli
        run: Q update-item
        env:
            Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
            Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
