name: Upload Figma Export to Q

on:
  repository_dispatch:
    types: [process-figma]
  workflow_dispatch:
    inputs:
      zipUrl:
        description: 'URL of the Figma export ZIP file'
        required: true
        type: string
      id:
        description: 'Production ID'
        required: true
        type: string

jobs:
  process-figma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true
          cache-dependency-path: pnpm-lock.yaml

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Process Figma Export
        run: pnpm process-figma "${{ github.event_name == 'repository_dispatch' && github.event.client_payload.zipUrl || inputs.zipUrl }}" "${{ github.event_name == 'repository_dispatch' && github.event.client_payload.id || inputs.id }}"

      - name: Build Svelte
        run: pnpm build

      - name: Install Q-CLI globally
        run: pnpm add -g @nzz/q-cli

      - name: Run Q cli
        run: Q update-item
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
